services:
  - type: web
    name: canvrio-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true